### ISSUE TITLE
Please remove sea "otters"

### ISSUE THREAD

**Issue by lucysrausch** [sivizius/otterapi#1]
I like your API, however I noticed it contains some sea "otters". Please remove them so I can enjoy you otter API without those bastards.

I found these:
`"https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/california-sea-otters.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/2000x860-cute-sea-otters-napping-in-eelgrass.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/Sea-otter-eating.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/Brook-Sea-Otter-1-30-191.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/2000x860-cute-sea-otter-fuzzy-cuteness.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/sea_otter_tony_trupp.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/sea-otter-hd-desktop-wallpaper-background-photos-free.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/header-sea-otters.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/1507203016-otter-seaweed.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/Julie-Larsen-Maher-2_4116_Sea-Otter_AQ_02-01-18_hr.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/seaottershav.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/sea_otter.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/sea-otter-swimming-in-blue-water-526331839-854a624208854ebc8473530b28ade5b8.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/header-sea-otter-reintroduction.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/header-sea-otter-reintroduction.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/NO_T31_LewisSealife01.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/skynews-sea-otter-otter_4526286.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/Seat-Otter.jpg",
    "https://raw.githubusercontent.com/sivizius/random-otters/master/public/otters/sea_otter_michael_peters_header.jpg",
"https://media.giphy.com/media/taYDEfNaR2QPm/source.gif",
    "https://media.giphy.com/media/H5bPs8B3vRCtW/giphy.gif"
`

I might have missed some others. They're easy to recognize:

True Otter:
- cute
- fluffy
- otter

Sea "Otters"
- they stink
- not fluffy
- rape and kill baby seals

Thanks

**Comment by sivizius** [comment]
All Otters Are Beautiful. Especially endangered Otters including Sea Otters.
